name: 💡 Feature Request
description: Suggest a feature for VinFast vehicles, app, or AVO website
title: "[FEATURE] "
labels: ["feature-request", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT DISCLAIMER**

        This tracker is for **community advocacy and documentation only**. AVO is an independent owner organization and is **NOT affiliated with VinFast Auto**.

        **Feature requests posted here are for community discussion and advocacy.** To request features directly from VinFast:
        - **VinFast Customer Support:** 1-888-689-3278 or [vinfastauto.us/support](https://vinfastauto.us/support)

        **Limitation of Liability:** AVO accepts no responsibility or ownership for feature requests. This tracker is provided as-is for community benefit. AVO does not guarantee that any feature will be implemented or that VinFast will respond to requests.

        ---

        **🔒 PRIVACY WARNING - PLEASE READ**

        **This issue will be PUBLIC and searchable on Google.** Anyone on the internet can read this forever.

        **DO NOT include:**
        - ❌ Full VIN numbers (last 4 digits only if absolutely needed)
        - ❌ License plate numbers
        - ❌ Your home address or personal address
        - ❌ Phone numbers or email addresses
        - ❌ Photos showing your face, license plates, or home
        - ❌ Full names of service center employees
        - ❌ Any other personal information you wouldn't want publicly searchable

        **Only share information you're comfortable being permanently public.**

        ---


        Thanks for suggesting a feature! Help us understand what you'd like to see.

  - type: dropdown
    id: feature-for
    attributes:
      label: Feature is for
      description: What is this feature request for?
      options:
        - VinFast Vehicle (hardware/software)
        - VinFast Mobile App
        - AVO Website
        - AVO Community/Services
        - Other
    validations:
      required: true

  - type: dropdown
    id: vehicle-model
    attributes:
      label: Which vehicle(s)?
      description: If vehicle-related, which models?
      options:
        - All models
        - VF8 only
        - VF9 only
        - VF6 only
        - VF5 only
        - Not vehicle-related

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: "Example: Add Auto-Park feature like Tesla's Smart Summon to VF9"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Why do you need this feature?
      placeholder: "Example: Parking in tight spots is difficult with a large SUV. This would make parking garages much easier."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Current Workarounds
      description: How do you handle this now?
      placeholder: "Example: Currently have to find larger parking spots or have someone guide me"

  - type: textarea
    id: implementation
    attributes:
      label: How should it work?
      description: Describe how you envision this feature working
      placeholder: |
        Example:
        1. Press Auto-Park button in app
        2. Vehicle pulls into parking spot automatically
        3. Distance sensors prevent collisions
        4. Works up to 20 feet away

  - type: dropdown
    id: priority
    attributes:
      label: Priority for you
      description: How important is this to you?
      options:
        - Critical - Would significantly improve ownership experience
        - High - Would be very useful
        - Medium - Nice to have
        - Low - Just an idea

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Examples from other brands, mockups, etc.
      placeholder: "Example: Tesla has this feature called Smart Summon. Here's how it works..."

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I've searched existing feature requests and this is not a duplicate
          required: true
